### ISSUE TITLE
Install error on win10

### ISSUE THREAD

**Issue by Tianxiaomo** [jpuigcerver/pytorch-baidu-ctc#2]
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    from torch.utils.cpp_extension import BuildExtension, CppExtension, CUDAExtension
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 61, in <module>
    CUDA_HOME = _find_cuda_home()
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 30, in _find_cuda_home
    if not os.path.exists(cuda_home):
  File "C:\ProgramData\Anaconda3\lib\genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not list

**Comment by jpuigcerver** [comment]
Only Linux is supported for now. But this seems a Pytorch issue, anyway.
